# Generated by Django 5.1.4 on 2026-06-13 13:48

import apps.jobs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("masters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField()),
                ("address", models.CharField(blank=True, max_length=200)),
                (
                    "price_type",
                    models.CharField(
                        choices=[("fixed", "Belgilangan narx"), ("negotiable", "Kelishiladi")],
                        default="fixed",
                        max_length=12,
                    ),
                ),
                (
                    "price_amount",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Mijoz taklif qilgan byudjet (soʻm) — faqat maʼlumot.",
                        null=True,
                    ),
                ),
                (
                    "payment_timing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("on_completion", "Ish yakunida"),
                            ("staged", "Bosqichma-bosqich"),
                            ("prepaid", "Oldindan kelishilgan"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "when_choice",
                    models.CharField(
                        choices=[
                            ("asap", "Imkon qadar tez"),
                            ("today", "Bugun"),
                            ("tomorrow", "Ertaga"),
                            ("this_week", "Shu hafta"),
                            ("exact", "Aniq sana"),
                        ],
                        default="this_week",
                        max_length=12,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("urgent", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ochiq"),
                            ("in_progress", "Bajarilmoqda"),
                            ("awaiting_confirmation", "Tasdiqlash kutilmoqda"),
                            ("completed", "Yakunlandi"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        default="open",
                        max_length=22,
                    ),
                ),
                ("proposals_count", models.PositiveIntegerField(default=0)),
                (
                    "assigned_master",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_jobs",
                        to="masters.masterprofile",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="catalog.category",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="catalog.city",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-urgent", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="JobEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("created", "Buyurtma joylandi"),
                            ("accepted", "Usta qabul qildi"),
                            ("started", "Ish boshlandi"),
                            ("in_progress", "Ish bajarilmoqda"),
                            ("awaiting", "Tasdiqlash kutilmoqda"),
                            ("completed", "Ish yakunlandi"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        max_length=14,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="JobImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to=apps.jobs.models.job_image_upload_to)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["status"], name="jobs_job_status_7d017a_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["urgent"], name="jobs_job_urgent_80e240_idx"),
        ),
    ]
