# Generated by Django 5.1.4 on 2026-06-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_backfill_job_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
