# Generated by Django 5.1.4 on 2026-06-13 13:48

import apps.masters.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bio", models.TextField(blank=True)),
                ("experience_years", models.PositiveSmallIntegerField(default=0)),
                (
                    "min_price",
                    models.PositiveIntegerField(
                        default=0, help_text="Minimal buyurtma narxi (soʻm)."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("free", "Boʻsh"), ("busy", "Band"), ("off", "Faol emas")],
                        default="free",
                        max_length=8,
                    ),
                ),
                ("is_top", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("rating_avg", models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                ("views_count", models.PositiveIntegerField(default=0)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="masters", to="catalog.category"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="master_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-is_top", "-rating_avg", "-reviews_count"),
            },
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=140)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("completed_at", models.DateField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=apps.masters.models.portfolio_upload_to
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.category",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio",
                        to="masters.masterprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "price_min",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("price_max", models.PositiveIntegerField(blank=True, null=True)),
                ("years", models.PositiveSmallIntegerField(default=0)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skills",
                        to="catalog.category",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="masters.masterprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("none", "Boshlanmagan"),
                            ("pending", "Tekshiruvda"),
                            ("approved", "Tasdiqlangan"),
                            ("rejected", "Rad etilgan"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "master",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to="masters.masterprofile",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verifications_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VerificationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("id", "Pasport / ID karta"),
                            ("selfie", "Selfi tekshiruvi"),
                            ("diploma", "Diplom / Sertifikat"),
                            ("address", "Manzil tasdigʻi"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to=apps.masters.models.verification_upload_to
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("none", "Yuklanmagan"),
                            ("uploaded", "Yuklandi"),
                            ("pending", "Tekshiruvda"),
                            ("verified", "Tasdiqlandi"),
                            ("rejected", "Rad etildi"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="masters.verificationrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("doc_type",),
            },
        ),
        migrations.AddIndex(
            model_name="masterprofile",
            index=models.Index(fields=["status"], name="masters_mas_status_879bc2_idx"),
        ),
        migrations.AddIndex(
            model_name="masterprofile",
            index=models.Index(fields=["is_verified"], name="masters_mas_is_veri_d1bc68_idx"),
        ),
        migrations.AddIndex(
            model_name="masterprofile",
            index=models.Index(fields=["is_top"], name="masters_mas_is_top_50ca74_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="verificationdocument",
            unique_together={("request", "doc_type")},
        ),
    ]
