# Generated by Django 5.1.4 on 2026-06-13 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaqTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.SlugField(max_length=40, unique=True)),
                ("label", models.CharField(max_length=80)),
                ("icon", models.CharField(default="help-circle", max_length=40)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("order", "label"),
            },
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="support.faqtopic",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
    ]
