# Generated by Django 5.1.4 on 2026-06-13 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("order", "Buyurtma"),
                            ("accepted", "Qabul qilindi"),
                            ("rejected", "Rad etildi"),
                            ("chat", "Xabar"),
                            ("system", "Tizim"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("body", models.CharField(blank=True, max_length=400)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("read", models.BooleanField(default=False)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["recipient", "read", "-created_at"],
                        name="notificatio_recipie_b41e6c_idx",
                    )
                ],
            },
        ),
    ]
